### ISSUE TITLE
Consider a higher resolution timer

### ISSUE THREAD

**Issue by HakShak** [honeycombio/beeline-python#100]
For python 2.7 we switched

https://github.com/honeycombio/beeline-python/blob/23ebbd1de2a0f1ed91576c9cb062422fce37bbe6/beeline/trace.py#L294

to 
```python
        self.event.start_time = time.clock()
```

and

https://github.com/honeycombio/beeline-python/blob/23ebbd1de2a0f1ed91576c9cb062422fce37bbe6/beeline/trace.py#L137-L138

to 

```python
            duration_ms = (time.clock() - span.event.start_time) * 1000
```

in order to get sub millisecond timings.

I'd PR this simple change, except:

```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.clock()
__main__:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
3.8311687
```

I checked https://github.com/benjaminp/six but there are no entries around the `time` module.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
