### ISSUE TITLE
Accept and issue OpenTelemetry/W3C style trace context (traceparent header)

### ISSUE THREAD

**Issue by garthk** [honeycombio/beeline-python#108]
G'day! We're propagating trace context around our environment using [W3C Trace Context](https://www.w3.org/TR/trace-context/#traceparent-header) _aka._ `traceparent` following the [OpenCensus convention](https://opencensus.io/api/python/_modules/opencensus/trace/propagation/trace_context_http_header_format.html) and [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/bdf39cb935a6f48badc687daeb78a66dc352761f/specification/trace/api.md#spancontext):

```
Traceparent: 00-D2E1605E07E0EEA1EDBCB72CA3DDEC23-50FEF9796F94C8B8-01
```

That doesn't fit so well with the `X-Honeycomb-Trace` header key hard-coded through this code base, preventing us using the beeline to help us send events to Honeycomb from ALL THE THINGS.

Strikes me the headers could be configurable, perhaps in such a way suppose the beelines could accept and issue both if necessary. You up for a PR for that?

**Comment by irvingpop** [comment]
Agreed!  In fact, we're planning to add this to the Beelines.  It's a slower effort for us because we need to think about feature parity in _all_ the language implementations.

Here' a summary of our intent:

We will be modifying each of the official beelines, as well as some of our agents to do the following:

* Automatically parse Honeycomb and W3C TraceContext headers included in incoming requests. If both header formats are present, the Honeycomb headers will be given precedence. Other header formats can be parsed with a callback function specified in the Beeline initialization (see example code).
* Outgoing HTTP requests will be instrumented according to a callback function specified in the Beeline initialization. This will allow users of beelines to make decisions about whether to instrument the outgoing request, or not (i.e. to avoid data leakage when making outbound calls to 3rd party APIs).


hey @paulosman @martin308 if @garthk contributed a PR along those lines would you be open to it, or do you already have an implementation you're rolling with?

**Comment by paulosman** [comment]
Thanks for the mention. Yup, this is on our roadmap and we're actively working on it! I'd avoid a PR to prevent duplicate work, but this issue will be mentioned when we have something ready to look at.

**Comment by JamieDanielson** [comment]
Sorry for the delayed response! This has since been added - see our [docs](https://docs.honeycomb.io/getting-data-in/python/beeline/#distributed-trace-propagation) for more details as needed.

#116 generates W3C-compliant headers, #122 and #123 adds parser and propagation hooks, and #199 detects incoming W3C headers and parses automatically. 🎉
