### ISSUE TITLE
Add field to current span and child spans only

### ISSUE THREAD

**Issue by dlmiddlecote** [honeycombio/beeline-python#110]
Hi there 👋

I was wondering if there’s a way to add a field to the current span, and its child spans, but not to its parent span, as currently happens with `add_trace_field`?

I know that I could manually add the fields to each span, but I’d love to not have to do that, if possible. 

My use case is iterating over multiple “accounts”, where the full iteration has a span, and each individual iteration has another span (and child spans), which attach the “account_id”. Using `add_trace_field` for the account_id mainly works as I’d like, expect the parent span also has the final account_id attached to it, which is undesirable.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
