### ISSUE TITLE
Attach query params to “requests” patch

### ISSUE THREAD

**Issue by dlmiddlecote** [honeycombio/beeline-python#111]
This may not be desirable behaviour for all integrations, but I’d love for the query parameters to be added to the event emitted when using the requests library. 

I wonder what people’s thoughts on this functionality are?

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
