### ISSUE TITLE
Flask `request.route` returns endpoint rather than "route".

### ISSUE THREAD

**Issue by SeanHood** [honeycombio/beeline-python#112]
I'm updating the beeline in one of our applications and found this in the changelog. And found `request.route` would clash with some instrumentation we already have. We've used `request.url_rule` from flask as the field value for `request.route`. For anyone not familiar this returns something like `/user/<username>`, rather than endpoint which returns the function name.

This is the line I'm referring to:
https://github.com/honeycombio/beeline-python/blob/0ca962081ab7093ea44410f5704cb49724fe34ec/beeline/middleware/flask/__init__.py#L39

I'm happy to PR a fix which would implement the following:
```python
beeline.add_field("request.endpoint", flask.request.endpoint)
beeline.add_field("request.route", flask.request.url_rule)
```

---

Other beeline's instrument the "pattern" of a request rather than the function name, some examples:
Go: https://github.com/honeycombio/beeline-go/blob/ca594899bf23a4e2496df8fd214bd7e0455ffb0f/wrappers/hnyecho/echo_test.go#L60
NodeJS/Express: (Returns: `/users/:user_id`) https://github.com/honeycombio/beeline-nodejs/blob/7e9ee85b5db91dce469770599019e78730ff12d0/lib/instrumentation/express.js#L143
Ruby: https://www.honeycomb.io/blog/honeybyte-beeline-dev-molly-struve/

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
