### ISSUE TITLE
Double "app." prefix in distributed trace fields

### ISSUE THREAD

**Issue by ajvondrak** [honeycombio/beeline-python#114]
The type checking done by https://github.com/honeycombio/beeline-python/blob/43a3f9b4f4e2844e7030b33f62695567332c73df/beeline/trace.py#L211-L214 was added by https://github.com/honeycombio/beeline-python/commit/70ad2e9f6b3674d3c9bb7a288a3f68ffdad36961 as an addendum to #96. But it fails to account for unicode types, which are returned by `json.loads` (at least in Python 2.7.12):
```python
>>> json.loads('{"app.field":"value"}')
{u'app.field': u'value'}
```
Thus, when `unmarshal_trace_context` parses a distributed trace header's fields with https://github.com/honeycombio/beeline-python/blob/43a3f9b4f4e2844e7030b33f62695567332c73df/beeline/trace.py#L352 and passes them into `add_trace_field` with the likes of https://github.com/honeycombio/beeline-python/blob/43a3f9b4f4e2844e7030b33f62695567332c73df/beeline/middleware/flask/__init__.py#L60-L63 then `type(u'app.field') == unicode`, not `str`, so it still gets coerced to `'app.app.field'`.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
