### ISSUE TITLE
Pyramid middleware?

### ISSUE THREAD

**Issue by jean** [honeycombio/beeline-python#129]
I'd like to use Honeycomb with Pyramid (https://trypyramid.com/)
I gave it a try like this, but I'm not seeing data show up at Honeycomb:

```python
if __name__ == "__main__":
    config = Configurator()
    config.add_route(ENDPOINT, "/{}".format(ENDPOINT))
    config.scan()

    app = config.make_wsgi_app()
    wrapped_app = HoneyWSGIMiddleware(app)
    server = make_server("0.0.0.0", 5000, wrapped_app)
    server.serve_forever()
```

Has anyone else done this already?

**Comment by irvingpop** [comment]
hi @jean !  Our Beeline might need changes to work properly in Pyramid, I don't know of anyone that's tried it yet.  I did however see that the OpenTelemetry team added support for Pyramid: https://github.com/open-telemetry/opentelemetry-python/pull/776

You could still use the OpenTelemetry agent to send data to Honeycomb using the `opentelemetry-ext-honeycomb` package.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
