### ISSUE TITLE
Beeline support for CherryPy

### ISSUE THREAD

**Issue by alsmith** [honeycombio/beeline-python#139]
Suggestion for supporting CherryPy here:

```
beeline.init(writekey=honeycombApiToken, dataset='xyz', service_name='something.or.other')

def reportBeeline(func):
    def wrapper(*args, **kwargs):
        trace = beeline.start_trace()
        beeline.add_context({'method': cherrypy.request.method, 'endpoint': cherrypy.request.path_info})
        try:
            result = func(*args, **kwargs)
        except Exception as e:
            beeline.finish_trace(trace)
            raise
        beeline.finish_trace(trace)
        return result
    return wrapper
```

Then, for each function that deals with a HTTP request, simply decorate it with the reportBeeline() decorator:

```
@cherrypy.tools.json_out(handler=dumper)
@reportBeeline
def servePage():
    return 'test'
```

**Comment by MikeGoldsmith** [comment]
Hi @alsmith  - thanks for raising the ticket. We'll take a look and get back to you on if / how we might support this.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
