### ISSUE TITLE
HoneyDBMiddleware gets db durations wrong with multiple threads

### ISSUE THREAD

**Issue by mattbennett** [honeycombio/beeline-python#162]
The query start time is being stashed on the shared object, rather than the thread-local storage:

https://github.com/honeycombio/beeline-python/blob/4bbbb9ae1279cab0a5a33c7533a783436e4d3916/beeline/middleware/flask/__init__.py#L107

As a consequence, db duration is incorrectly calculated when multiple concurrent threads are running.

Here's a simple repro:

``` python
import os
import time

import beeline
from beeline.middleware.flask import HoneyMiddleware
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

beeline.init(
    writekey=os.environ.get("HONEYCOMB_API_KEY"),
    dataset="concurrency-test",
    service_name="busted",
    debug=True,
)

# Pass your Flask app to HoneyMiddleware
app = Flask(__name__)
app.config[
    "SQLALCHEMY_DATABASE_URI"
] = "postgresql://postgres:password@localhost/honeycomb_test"
db = SQLAlchemy(app)

HoneyMiddleware(
    app, db_events=True
)  # db_events defaults to True, set to False if not using our db middleware with Flask-SQLAlchemy


@app.route("/sleep/<seconds>")
def sleepy(seconds):
    time.sleep(1)
    db.session.execute(f"SELECT pg_sleep({seconds})")
    time.sleep(1)
    return f"yawn! (slept {int(seconds) + 2} seconds)"

```

Call it with this script

```
curl http://localhost:5000/sleep/5 &
sleep 4
curl http://localhost:5000/sleep/5 
```

The second call generates a database span that has a five-second duration, but the `db.duration` is reported as ~1s.

![Screenshot 2021-03-18 at 16 49 36](https://user-images.githubusercontent.com/107611/111666728-e43aab00-880b-11eb-8ebc-0301bb4b71ad.png)

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
