### ISSUE TITLE
Root span never closed if status code is 500

### ISSUE THREAD

**Issue by mitchfriedman** [honeycombio/beeline-python#164]
I'm not entirely sure for the reason of this bit of code (https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/flask/__init__.py#L48-L52), but if I catch an exception in my code (logging with sentry), then if I return a 500 status code the root trace is never closed, and it shows up as missing the root trace in the Honeycomb trace view.

I temporarily worked around this by patching the honeycomb middleware:
```
class PatchedHoneyWSGIMiddleware(object):
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        req = Request(environ, shallow=True)
        wr = WSGIRequest("flask", environ)

        root_span = beeline.propagate_and_start_trace(wr.request_context(), wr)

        def _start_response(status, headers, *args):
            status_code = int(status[0:4])
            beeline.add_context_field("response.status_code", status_code)
            beeline.finish_trace(root_span)

            return start_response(status, headers, *args)

        return self.app(environ, _start_response)


beeline.middleware.flask.HoneyWSGIMiddleware = PatchedHoneyWSGIMiddleware
```
making sure to always close the trace root, but this is probably missing something.

**Comment by MatthewMiele** [comment]
I've just run into what seems to be the same issue. It looks like the problem is with this line 

https://github.com/honeycombio/beeline-python/blob/7c5268e2855759f39d443ffef3291c37714c4178/beeline/middleware/flask/__init__.py#L51

specifically the signals check ```and not signals.signals_available```.
for me `signals.signals_available` is True.

For signals to work in Flask you need a library called `blinker`. When I remove blinker, `signals.signals_available` becomes False and my error spans are restored.

I think the real bug might lie in this file / with how Honeycomb is using signals?
https://github.com/honeycombio/beeline-python/blob/7c5268e2855759f39d443ffef3291c37714c4178/beeline/middleware/flask/__init__.py#L18-L19
specifically in this function
https://github.com/honeycombio/beeline-python/blob/7c5268e2855759f39d443ffef3291c37714c4178/beeline/middleware/flask/__init__.py#L27-L33
It seems like it adds a callback for Flask signals to call at the end of the request but for me the exception that is being based in is `None` and I believe this is due to already being handled by my custom error handlers in Flask. By the time the code gets here there is no Exception, its now just a normal response object that is a 500 with some json.
