### ISSUE TITLE
Duration math is done with naive datetime objects, won't handle clock changes mid-process

### ISSUE THREAD

**Issue by estein-de** [honeycombio/beeline-python#223]
https://github.com/honeycombio/beeline-python/blob/23ebbd1de2a0f1ed91576c9cb062422fce37bbe6/beeline/middleware/flask/__init__.py#L147

Looking at this, in situations where the app is running in a timezone (not UTC) that has daylight savings, when a request started before the fall-back or spring-forward and finished after it, won't the number be wrong?

**Comment by robbkidd** [comment]
🤔 

![It's a possibility.](https://user-images.githubusercontent.com/517302/168675970-99696517-abea-42c2-9b72-eedf6068f6d6.gif)

Because we have dropped support for Python < 3.5, we could use [`time.monotonic()`](https://docs.python.org/3/library/time.html#time.monotonic) for the calculation of duration to better survive system clock updates (timezone changes, clock skew corrections, etc.).
 
Have you noticed inaccurate durations in your data, @estein-de? Or was this found while reading the code?

**Comment by estein-de** [comment]
Just found this while reading code. I have not gone looking into the data. It seemed pretty straightforward that a problem would exist without needing to prove it so I didn't bother.

**Comment by estein-de** [comment]
`datetime.datetime.now` in both python 3.8 (what I just happened to test with) and my recollection of what the documented behavior is in the CPython docs is, is that it uses the current local time and returns a naive timestamp. This just goes back to the python datetime module being designed in a way that I would consider "wrong" with the benefit of 20/20 hindsight.

**Comment by vreynolds** [comment]
Hello,

We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
