### ISSUE TITLE
[flask-sqlalchemy] Generated db.query seems to include source code file + line

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-python#38]
This should probably be its own field.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
