### ISSUE TITLE
docs refer to parent_span_id instead of parent_id

### ISSUE THREAD

**Issue by lavie** [honeycombio/beeline-python#49]
Specifically, this page: https://docs.honeycomb.io/beeline/python/#using-traces

The name of the argument passed to the context manager is `parent_id` and not `parent_span_id`.

**Comment by tredman** [comment]
I don't see a reference to `parent_span_id` where the docs discuss the context manager on that page. There is a `parent_span_id` parameter in `start_trace` and the difference there is intentional: to clarify that the parent's span id is being asked for and not the parent's trace id.

It does look like we do not document `tracer` well enough in the docstrings (which are used in generating the reference docs here: https://honeycombio.github.io/beeline-python/). I'm going to keep this issue open to make some changes to those docs.

**Comment by MikeGoldsmith** [comment]
The docs have been updated since this issue was first opened - closing now. Feel free to re-open if it’s still relevant.
