### ISSUE TITLE
honeycomb seems to be lagging after the request is done

### ISSUE THREAD

**Issue by posix4e** [honeycombio/beeline-python#56]
We seem to be experiencing lag in the after request. Honeycomb currently uses the after_request . This is not a reasonable solution https://stackoverflow.com/questions/48994440/execute-a-function-after-flask-returns-response. We use gunicorn, perhaps we can move it after the request to your backend there. Also I noticed there's no logging at all if we can't connect to the honeycomb backend.

**Comment by posix4e** [comment]
![image](https://user-images.githubusercontent.com/806363/51931330-5d1ee480-23b1-11e9-9b1d-a1761fef408d.png)

**Comment by posix4e** [comment]
That last trace is where our request ends. However it seems as though we lag for 10 seconds more.

**Comment by e271828-** [comment]
Agree with this. Our preferred pattern for analytics is to let the service call `export()` and get a dict to store in a local queue, then `send(dict)` from an out-of-band worker.

**Comment by tredman** [comment]
Hey, thanks for the report.

It's true that `after_request` is synchronous, but the beeline does not make an API request to our backend inside `after_request`. Instead, when we finish the trace, we put the event on a queue that gets processed asynchronously by another thread, so the overhead the beeline is imposing on flask requests should be minimal, and certainly not 10 seconds in the usual case. An exception to this might be if you configured the beeline with `block_on_send=True` - this would cause the event queue to block if full. we don't run with this option by default.

I'm not ruling out the possibility that we're introducing lag, but I would be surprised if that's the case given that we talk to the backend asynchronously. Curious if you swap out the default transmission with a FileTransmission, do you still experience the lag? See here for an example: https://docs.honeycomb.io/beeline/python/#customizing-event-transmission - basically the beeline will work like normal, except rather than logging to our API it will write events to stderr. You can still look at `duration_ms` in the output and see if the requests are taking 10s+.

Are you experiencing this lag on all requests? If so is this under high volume or is there any other context you can provide? 

>  Also I noticed there's no logging at all if we can't connect to the honeycomb backend.

Can you elaborate here? Do you mean debug logging or something else?

**Comment by posix4e** [comment]
Yea, i set your production server to 1.2.3.4 on /etc/hosts and got no error msgs in my logs. I was surprised. Also I'm curious if you have some good line numbers for us to take a look at how you do it asyncronouysly. We might try to do something familiar.

**Comment by tredman** [comment]
Ah - no we don't log errors by default. You can enable that by turning on debug mode: https://docs.honeycomb.io/beeline/python/#troubleshooting-the-beeline - this should log errors connecting to the API, for example.

re: sending events async, when the request ends we call `finish_trace` here:
https://github.com/honeycombio/beeline-python/blob/master/beeline/middleware/flask/__init__.py#L80

This ultimately calls an internal function called `_run_hooks_and_send` which calls `send_presampled` on the underlying event:
https://github.com/honeycombio/beeline-python/blob/master/beeline/trace.py#L213

In libhoney, where lower-level interaction with the API is defined, `send_presampled` ultimately calls `send` in the transmission implementation, which puts it on the queue.
https://github.com/honeycombio/libhoney-py/blob/master/libhoney/transmission.py#L77

The queue is processed by the `_sender` function, which gets started in a background thread at init time:
https://github.com/honeycombio/libhoney-py/blob/master/libhoney/transmission.py#L106

That roughly covers how events get to the API, although I am sure I skipped some steps. Happy to help debug further.
