### ISSUE TITLE
Add support for the `dataset` field in the trace propagation header

### ISSUE THREAD

**Issue by maplebed** [honeycombio/beeline-python#61]
The Go beeline supports adding a `dataset` field to the trace propagation header (`x-honeycomb-trace`). The effect of including this field is that spans from the downstream service should be sent to the indicated dataset. The rest of the beelines should implement this addition.

**Comment by Vlaaaaaaad** [comment]
Welp, `unmarshal_trace_context` fails completely due to this. 

The Golang beeline sends the `dataset` too so there are 4 key-value pairs. The beeline-python logic [is specifically looking for 3 values](https://github.com/honeycombio/beeline-python/blob/d2be775758e29f49e58799c45736d93759616e6c/beeline/trace.py#L296-L298`).

Maybe a version 2 should've been used when `dataset` was added.

**Comment by tredman** [comment]
At this point it seems like fixing this would be a breaking change. As a user, if my minor patch fix started routing my events to a different dataset I might get annoyed. We could fix the unmarshal function to at least support the fourth value even if we discard the dataset.

**Comment by twpol** [comment]
If it's considered a breaking change, could it be turned on as an option when configuring the Beeline? It's pretty sad to have implemented Beelines across multiple services in different languages and only get partially working tracing out.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
