### ISSUE TITLE
AWS botocore.vendored.requests does not get patched with beeline.patch

### ISSUE THREAD

**Issue by lewisf** [honeycombio/beeline-python#79]
AWS `boto3` uses `botocore` and `botocore` seems to bring its own `requests` @ `botocore.vendored.requests`, which does not get patched.

I've managed to get something working on my end by copying the patch to patch `botocore.vendored.requests` as well.

can this MAYBE happen within beeline-python? or is that maybe too much to ask? or is there another recommendation?

**Comment by tredman** [comment]
As long as it's optional I think we could do something like that in the beeline. I am a bit wary of patching something like boto by default with the `requests` patch but I think a `patch.boto` module would make sense. Any interest in submitting your patch as a PR?

**Comment by mickeypash** [comment]
Hello! I'm also interested in being able to instrument Boto. @lewisf  could you elaborate on how you tackled the issue. I know it's been a while no worries if you can't recall!
Also for anyone else who stumbles onto this page I came across [OpenTelemetry's approach to patching Boto](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/master/instrumentation/opentelemetry-instrumentation-boto/src/opentelemetry/instrumentation/boto/__init__.py) which might be useful.

**Comment by mickeypash** [comment]
Coincidentally I came across an article which mentioned that[ botocore has removed the vendored version of requests](https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/).

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
