### ISSUE TITLE
Inconsistent field name for User-Agent header across Beelines

### ISSUE THREAD

**Issue by jgjay** [honeycombio/beeline-python#83]
The Python Beeline adds a field for the User-Agent to the `http_server` spans it creates:

https://github.com/honeycombio/beeline-python/blob/ec05745807d937fe4b066d6c65adeba9cf495237/beeline/middleware/flask/__init__.py#L87

The field name `request.user_agent` is inconsistent with the other Beelines which use `request.header.user_agent`:

* [beeline-go](https://github.com/honeycombio/beeline-go/blob/c5184e06240056096fbe13f676f02aea2fa4b9b5/wrappers/common/common.go#L87)
* [beeline-ruby](https://github.com/honeycombio/beeline-ruby/blob/a0998861164dc7951860f0d35921563b49127cb3/lib/honeycomb/integrations/rack.rb#L16)
* [beeline-java](https://github.com/honeycombio/beeline-java/blob/6fe96ad3159c772dd1dba7a2bad05dffccbbf66e/beeline-core/src/main/java/io/honeycomb/beeline/tracing/utils/TraceFieldConstants.java#L65)

It would be great if these could be consistent to ease querying in deployments with polyglot services.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
