### ISSUE TITLE
Allow not logging parameters for DB requests

### ISSUE THREAD

**Issue by sjoerdjob** [honeycombio/beeline-python#99]
In the Django beeline, we see that `db.query_args` is always added to the context when making a query.

https://github.com/honeycombio/beeline-python/blob/master/beeline/middleware/django/__init__.py#L28

It would be nice if this would be somewhat overrideable, similarly to how it's now possible to do so for the Middleware, since https://github.com/honeycombio/beeline-python/pull/73/files.

They way I think this would be best achievable would be to:

1. Add a class attribute to `HoneyMiddleware` which specifies which class the `db_wrapper` has.
2. Make the dictionary for the first `beeline.add_context` the result of another callable on the `HoneyDBWrapper` class.

Alternatively, this could of course also be handled by a presend hook.

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
